version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: juegosHistorial
    environment:
      POSTGRES_DB: game_historial_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

